### ISSUE TITLE
Checklist for Bridge devnet deployment

### ISSUE THREAD

**Issue by 0xmovses** [movementlabsxyz/movement#639]
**Checklist**
- [x] Add oneshot smart contract logic to update total locked amount on ETH
- [ ] Pull in new aptos-core rev and update relayer and tests to use framework bridge module. In progress @andygolay 
- [ ] Create upgrade tx for `aptos-core` @andyjsbell 
- [ ] Switch on bridge feature in `aptos-core` via the script @andyjsbell 
- [ ] Config / Godfig logic In progress @musitdev 
- [ ] e2e test @musitdev
- [ ] Update Dockercompose and Terrafrom files for infra In progress @l-monninger 
- [ ] Deploy the eth smart contracts to sepolia testnet 
- [x] Update cli to manage transfer on all chain.
- [ ] Indexer bridge processor to index all BridgeTransfers for FE and UX
- [ ] Disable the faucet

**Comment by andyjsbell** [comment]
Looks like we have deployed the open network to devnet so probably best to run a upgrade over tx

**Comment by 0xmovses** [comment]
Ah, I don't understand why open network is blocking? Or is it more of a best practice from SRE? @radupopa369 feel free to chime in. I'm trying to understand why we need open network prior to bridge being shipped.

To the upgrade point, if we have more than one node, yes we will need to upgrade over the wire via a tx as you explained, thanks.

**Comment by 0xmovses** [comment]
I just understood that the open-network PR is inside devnet, that's cool! So you upgrade over the tx.
